# Generated by Django 4.0.2 on 2022-02-21 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_no', models.IntegerField(default=1)),
                ('b_title', models.CharField(max_length=1000)),
                ('b_content', models.TextField(null=True)),
                ('b_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 21, 20, 27, 44, 741512))),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
        ),
    ]
