# Generated by Django 4.0.2 on 2022-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('u_firtname', models.CharField(max_length=32)),
                ('u_lastname', models.CharField(max_length=32)),
                ('u_eamil', models.EmailField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('u_pw', models.CharField(max_length=64)),
                ('u_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
